"""Add extended structured tables

Revision ID: 0b069f7db400
Revises: 
Create Date: 2026-08-06 22:11:12.737631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b069f7db400'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_quality_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('variety', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('min_size_mm', sa.Float(), nullable=True),
    sa.Column('max_moisture_pct', sa.Float(), nullable=True),
    sa.Column('color_standards', sa.String(), nullable=True),
    sa.Column('skin_firmness', sa.String(), nullable=True),
    sa.Column('common_defects_allowed', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_quality_references_crop'), 'crop_quality_references', ['crop'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_table('market_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('market_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_mappings_district'), 'market_mappings', ['district'], unique=False)
    op.create_table('msp_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crop', sa.String(), nullable=False),
    sa.Column('crop_full_name', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('msp_price_per_quintal', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msp_prices_crop'), 'msp_prices', ['crop'], unique=False)
    op.create_table('negotiations',
    sa.Column('negotiation_id', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('negotiation_id')
    )
    op.create_table('offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('negotiation_id', sa.String(), nullable=True),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_negotiation_id'), 'offers', ['negotiation_id'], unique=False)
    op.create_table('produce',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasonal_calendar',
    sa.Column('season_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('month_range', sa.String(), nullable=False),
    sa.Column('affected_crops', sa.String(), nullable=False),
    sa.Column('price_impact_trend', sa.String(), nullable=False),
    sa.Column('market_behavior_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('season_id')
    )
    op.create_table('transporters',
    sa.Column('transporter_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('capacity_mt', sa.Float(), nullable=False),
    sa.Column('rate_per_km', sa.Float(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('transporter_id')
    )
    op.create_table('trust_scores',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('fulfillment_rate', sa.Float(), nullable=False),
    sa.Column('payment_punctuality', sa.Float(), nullable=False),
    sa.Column('total_completed_deals', sa.Integer(), nullable=False),
    sa.Column('contract_breaches', sa.Integer(), nullable=False),
    sa.Column('trust_score_final', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('verification_docs', sa.String(), nullable=False),
    sa.Column('preferences', sa.String(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('capacity_mt', sa.Float(), nullable=False),
    sa.Column('available_capacity_mt', sa.Float(), nullable=False),
    sa.Column('price_per_mt_per_day', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_index(op.f('ix_warehouses_district'), 'warehouses', ['district'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_district'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trust_scores')
    op.drop_table('transporters')
    op.drop_table('seasonal_calendar')
    op.drop_table('produce')
    op.drop_index(op.f('ix_offers_negotiation_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_table('negotiations')
    op.drop_index(op.f('ix_msp_prices_crop'), table_name='msp_prices')
    op.drop_table('msp_prices')
    op.drop_index(op.f('ix_market_mappings_district'), table_name='market_mappings')
    op.drop_table('market_mappings')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_table('history')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_crop_quality_references_crop'), table_name='crop_quality_references')
    op.drop_table('crop_quality_references')
    op.drop_table('contracts')
    op.drop_table('buyers')
    # ### end Alembic commands ###
