"""initial_schema

Revision ID: 3b81df815c54
Revises: 
Create Date: 2026-08-08 09:44:10.536580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b81df815c54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('buyer_name', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('crop', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('min_price', sa.Float(), nullable=True))
    op.add_column('buyers', sa.Column('max_price', sa.Float(), nullable=True))
    op.add_column('buyers', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('buyers', sa.Column('location', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('urgency', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('neg_mode', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('strategy', sa.String(), nullable=True))
    op.add_column('buyers', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_buyers_user_id'), 'buyers', ['user_id'], unique=False)
    op.drop_column('buyers', 'data')
    op.add_column('contracts', sa.Column('negotiation_id', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('farmer_id', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('buyer_id', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('crop', sa.String(), nullable=True))
    op.add_column('contracts', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('final_price', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('contracts', 'data')
    op.add_column('history', sa.Column('negotiation_id', sa.String(), nullable=True))
    op.add_column('history', sa.Column('crop', sa.String(), nullable=True))
    op.add_column('history', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('status', sa.String(), nullable=True))
    op.add_column('history', sa.Column('final_price', sa.Float(), nullable=True))
    op.add_column('history', sa.Column('summary', sa.String(), nullable=True))
    op.drop_column('history', 'data')
    op.add_column('negotiations', sa.Column('crop', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('negotiations', sa.Column('farmer_id', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('buyer_id', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('farmer_name', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('status', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('current_round', sa.Integer(), nullable=False))
    op.add_column('negotiations', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('final_price', sa.Float(), nullable=True))
    op.add_column('negotiations', sa.Column('transport_plan', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('peer_node', sa.String(), nullable=True))
    op.add_column('negotiations', sa.Column('logs', sa.JSON(), nullable=True))
    op.add_column('negotiations', sa.Column('market_offers', sa.JSON(), nullable=True))
    op.add_column('negotiations', sa.Column('selected_buyer', sa.JSON(), nullable=True))
    op.add_column('negotiations', sa.Column('signatures', sa.JSON(), nullable=True))
    op.drop_column('negotiations', 'data')
    op.add_column('offers', sa.Column('sender', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('offers', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('offers', sa.Column('message', sa.String(), nullable=True))
    op.drop_column('offers', 'data')
    op.add_column('produce', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('produce', sa.Column('farmer_name', sa.String(), nullable=True))
    op.add_column('produce', sa.Column('crop', sa.String(), nullable=True))
    op.add_column('produce', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('produce', sa.Column('min_price', sa.Float(), nullable=True))
    op.add_column('produce', sa.Column('shelf_life', sa.Integer(), nullable=True))
    op.add_column('produce', sa.Column('location', sa.String(), nullable=True))
    op.add_column('produce', sa.Column('quality', sa.String(), nullable=True))
    op.add_column('produce', sa.Column('language', sa.String(), nullable=True))
    op.add_column('produce', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_produce_user_id'), 'produce', ['user_id'], unique=False)
    op.drop_column('produce', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produce', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_produce_user_id'), table_name='produce')
    op.drop_column('produce', 'status')
    op.drop_column('produce', 'language')
    op.drop_column('produce', 'quality')
    op.drop_column('produce', 'location')
    op.drop_column('produce', 'shelf_life')
    op.drop_column('produce', 'min_price')
    op.drop_column('produce', 'quantity')
    op.drop_column('produce', 'crop')
    op.drop_column('produce', 'farmer_name')
    op.drop_column('produce', 'user_id')
    op.add_column('offers', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('offers', 'message')
    op.drop_column('offers', 'quantity')
    op.drop_column('offers', 'price')
    op.drop_column('offers', 'sender')
    op.add_column('negotiations', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('negotiations', 'signatures')
    op.drop_column('negotiations', 'selected_buyer')
    op.drop_column('negotiations', 'market_offers')
    op.drop_column('negotiations', 'logs')
    op.drop_column('negotiations', 'peer_node')
    op.drop_column('negotiations', 'transport_plan')
    op.drop_column('negotiations', 'final_price')
    op.drop_column('negotiations', 'summary')
    op.drop_column('negotiations', 'current_round')
    op.drop_column('negotiations', 'status')
    op.drop_column('negotiations', 'farmer_name')
    op.drop_column('negotiations', 'user_id')
    op.drop_column('negotiations', 'buyer_id')
    op.drop_column('negotiations', 'farmer_id')
    op.drop_column('negotiations', 'quantity')
    op.drop_column('negotiations', 'crop')
    op.add_column('history', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('history', 'summary')
    op.drop_column('history', 'final_price')
    op.drop_column('history', 'status')
    op.drop_column('history', 'quantity')
    op.drop_column('history', 'crop')
    op.drop_column('history', 'negotiation_id')
    op.add_column('contracts', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('contracts', 'status')
    op.drop_column('contracts', 'final_price')
    op.drop_column('contracts', 'quantity')
    op.drop_column('contracts', 'crop')
    op.drop_column('contracts', 'buyer_id')
    op.drop_column('contracts', 'farmer_id')
    op.drop_column('contracts', 'negotiation_id')
    op.add_column('buyers', sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_buyers_user_id'), table_name='buyers')
    op.drop_column('buyers', 'status')
    op.drop_column('buyers', 'strategy')
    op.drop_column('buyers', 'neg_mode')
    op.drop_column('buyers', 'urgency')
    op.drop_column('buyers', 'location')
    op.drop_column('buyers', 'quantity')
    op.drop_column('buyers', 'max_price')
    op.drop_column('buyers', 'min_price')
    op.drop_column('buyers', 'crop')
    op.drop_column('buyers', 'buyer_name')
    op.drop_column('buyers', 'user_id')
    # ### end Alembic commands ###

