import asyncio
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, ".")
from sqlalchemy import text
from database.db import engine

ENRICHED_LISTINGS = [
    # Soybean Mandis (Latur, Nanded, Akola, Washim, Parbhani, Hingoli)
    {
        "id": "prod_soybean_latur_01",
        "user_id": "usr_farmer_ramesh",
        "farmer_name": "Ramesh Patil",
        "crop": "Soybean",
        "crop_category": "Oilseeds",
        "variety": "JS-335",
        "grade": "A",
        "quantity": 1500.0,
        "unit": "kg",
        "min_sale_quantity": 100.0,
        "expected_price": 78.0,
        "min_price": 70.0,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 9.5, "oil_content_pct": 19.5, "grade_standards": "APMC Grade A"},
        "harvest_date": "2026-08-20", "availability_date": "2026-08-25", "preferred_selling_date": "2026-09-15",
        "shelf_life": 180, "location": "Latur APMC, Latur, Maharashtra", "latitude": 18.4088, "longitude": 76.5604,
        "images": ["/crops/soybean.jpg"], "description": "Premium Grade A JS-335 Soybean, low moisture, 19.5% oil.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_soybean_nanded_02",
        "user_id": "usr_farmer_suresh",
        "farmer_name": "Suresh Deshmukh",
        "crop": "Soybean",
        "crop_category": "Oilseeds",
        "variety": "MAUS-71",
        "grade": "A",
        "quantity": 2500.0,
        "unit": "kg",
        "min_sale_quantity": 200.0,
        "expected_price": 74.0,
        "min_price": 68.5,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 9.0, "oil_content_pct": 19.8, "grade_standards": "APMC Grade A"},
        "harvest_date": "2026-08-22", "availability_date": "2026-08-27", "preferred_selling_date": "2026-09-18",
        "shelf_life": 180, "location": "Nanded APMC, Nanded, Maharashtra", "latitude": 19.1383, "longitude": 77.3210,
        "images": ["/crops/soybean.jpg"], "description": "High-yield MAUS-71 variety, harvested with automated thresher.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_soybean_akola_03",
        "user_id": "usr_farmer_vilas",
        "farmer_name": "Vilas Jadhav",
        "crop": "Soybean",
        "crop_category": "Oilseeds",
        "variety": "JS-9305",
        "grade": "B",
        "quantity": 3000.0,
        "unit": "kg",
        "min_sale_quantity": 500.0,
        "expected_price": 75.0,
        "min_price": 71.0,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 10.2, "oil_content_pct": 19.1, "grade_standards": "APMC Grade B"},
        "harvest_date": "2026-08-25", "availability_date": "2026-08-29", "preferred_selling_date": "2026-09-20",
        "shelf_life": 180, "location": "Akola APMC, Akola, Maharashtra", "latitude": 20.7002, "longitude": 77.0082,
        "images": ["/crops/soybean.jpg"], "description": "Clean Vidarbha soybean, suitable for feed mills and processing units.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_soybean_washim_04",
        "user_id": "usr_farmer_anand",
        "farmer_name": "Anand Shinde",
        "crop": "Soybean",
        "crop_category": "Oilseeds",
        "variety": "JS-335",
        "grade": "A",
        "quantity": 1200.0,
        "unit": "kg",
        "min_sale_quantity": 100.0,
        "expected_price": 76.0,
        "min_price": 69.0,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 9.2, "oil_content_pct": 20.1, "grade_standards": "APMC Grade A"},
        "harvest_date": "2026-08-26", "availability_date": "2026-08-30", "preferred_selling_date": "2026-09-22",
        "shelf_life": 180, "location": "Washim APMC, Washim, Maharashtra", "latitude": 20.1065, "longitude": 77.1350,
        "images": ["/crops/soybean.jpg"], "description": "Certified organic soybean, zero chemical pesticide residue.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_soybean_parbhani_05",
        "user_id": "usr_farmer_nitin",
        "farmer_name": "Nitin Chavan",
        "crop": "Soybean",
        "crop_category": "Oilseeds",
        "variety": "MAUS-158",
        "grade": "A",
        "quantity": 4000.0,
        "unit": "kg",
        "min_sale_quantity": 500.0,
        "expected_price": 77.5,
        "min_price": 72.0,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 9.4, "oil_content_pct": 19.6, "grade_standards": "APMC Grade A"},
        "harvest_date": "2026-08-21", "availability_date": "2026-08-26", "preferred_selling_date": "2026-09-17",
        "shelf_life": 180, "location": "Parbhani APMC, Parbhani, Maharashtra", "latitude": 19.2608, "longitude": 76.7749,
        "images": ["/crops/soybean.jpg"], "description": "Large bulk lot available for immediate dispatch. Stored in dry warehouse.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_soybean_hingoli_06",
        "user_id": "usr_farmer_ganesh",
        "farmer_name": "Ganesh Kadam",
        "crop": "Soybean",
        "crop_category": "Oilseeds",
        "variety": "JS-335",
        "grade": "A",
        "quantity": 2000.0,
        "unit": "kg",
        "min_sale_quantity": 200.0,
        "expected_price": 73.0,
        "min_price": 67.5,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 8.9, "oil_content_pct": 19.7, "grade_standards": "APMC Grade A"},
        "harvest_date": "2026-08-24", "availability_date": "2026-08-28", "preferred_selling_date": "2026-09-19",
        "shelf_life": 180, "location": "Hingoli APMC, Hingoli, Maharashtra", "latitude": 19.7196, "longitude": 77.1485,
        "images": ["/crops/soybean.jpg"], "description": "Very low moisture content, ideal for storage and solvent extraction.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },

    # Cotton Mandis (Amravati, Yavatmal, Wardha, Nagpur)
    {
        "id": "prod_cotton_amravati_01",
        "user_id": "usr_farmer_arjun",
        "farmer_name": "Arjun Kale",
        "crop": "Cotton",
        "crop_category": "Commercial Cash Crops",
        "variety": "Bt Cotton (Medium Staple)",
        "grade": "A",
        "quantity": 2000.0,
        "unit": "kg",
        "min_sale_quantity": 200.0,
        "expected_price": 72.0,
        "min_price": 62.0,
        "price_unit": "per_kg",
        "quality_info": {"staple_length_mm": 28.5, "trash_content_pct": 2.1, "moisture_pct": 7.8},
        "harvest_date": "2026-08-22", "availability_date": "2026-08-28", "preferred_selling_date": "2026-09-18",
        "shelf_life": 365, "location": "Amravati APMC, Amravati, Maharashtra", "latitude": 20.9374, "longitude": 77.7796,
        "images": ["/crops/cotton.jpg"], "description": "Bright white medium staple Bt cotton, free of staining.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_cotton_yavatmal_02",
        "user_id": "usr_farmer_balasaheb",
        "farmer_name": "Balasaheb Wagh",
        "crop": "Cotton",
        "crop_category": "Commercial Cash Crops",
        "variety": "Bt Cotton (Long Staple)",
        "grade": "A",
        "quantity": 3500.0,
        "unit": "kg",
        "min_sale_quantity": 500.0,
        "expected_price": 74.0,
        "min_price": 64.0,
        "price_unit": "per_kg",
        "quality_info": {"staple_length_mm": 30.2, "trash_content_pct": 1.8, "moisture_pct": 7.5},
        "harvest_date": "2026-08-24", "availability_date": "2026-08-30", "preferred_selling_date": "2026-09-20",
        "shelf_life": 365, "location": "Yavatmal APMC, Yavatmal, Maharashtra", "latitude": 20.3888, "longitude": 78.1204,
        "images": ["/crops/cotton.jpg"], "description": "Premium long staple cotton suitable for high-count yarn spinning.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_cotton_wardha_03",
        "user_id": "usr_farmer_sanjay",
        "farmer_name": "Sanjay Rathod",
        "crop": "Cotton",
        "crop_category": "Commercial Cash Crops",
        "variety": "Bt Cotton",
        "grade": "B",
        "quantity": 1800.0,
        "unit": "kg",
        "min_sale_quantity": 200.0,
        "expected_price": 70.0,
        "min_price": 61.5,
        "price_unit": "per_kg",
        "quality_info": {"staple_length_mm": 27.5, "trash_content_pct": 2.5, "moisture_pct": 8.1},
        "harvest_date": "2026-08-20", "availability_date": "2026-08-25", "preferred_selling_date": "2026-09-15",
        "shelf_life": 365, "location": "Wardha APMC, Wardha, Maharashtra", "latitude": 20.7453, "longitude": 78.6022,
        "images": ["/crops/cotton.jpg"], "description": "Standard ginning grade cotton from Sevagram belt.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },

    # Onion Mandis (Lasalgaon, Pimpalgaon, Yeola, Kalwan)
    {
        "id": "prod_onion_nashik_01",
        "user_id": "usr_farmer_sita",
        "farmer_name": "Sita Deshmukh",
        "crop": "Onion",
        "crop_category": "Bulb Vegetables",
        "variety": "Bhima Red",
        "grade": "A",
        "quantity": 2500.0,
        "unit": "kg",
        "min_sale_quantity": 250.0,
        "expected_price": 26.0,
        "min_price": 20.0,
        "price_unit": "per_kg",
        "quality_info": {"bulb_diameter_mm": 55.0, "skin_firmness": "Tight double wrapper scales"},
        "harvest_date": "2026-08-15", "availability_date": "2026-08-20", "preferred_selling_date": "2026-09-10",
        "shelf_life": 90, "location": "Lasalgaon Mandi, Nashik, Maharashtra", "latitude": 20.1478, "longitude": 74.2259,
        "images": ["/crops/onion.jpg"], "description": "High-firmness Lasalgaon red onion, export grade.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_onion_pimpalgaon_02",
        "user_id": "usr_farmer_pandurang",
        "farmer_name": "Pandurang Shinde",
        "crop": "Onion",
        "crop_category": "Bulb Vegetables",
        "variety": "Bhima Super",
        "grade": "A",
        "quantity": 4000.0,
        "unit": "kg",
        "min_sale_quantity": 500.0,
        "expected_price": 25.5,
        "min_price": 19.5,
        "price_unit": "per_kg",
        "quality_info": {"bulb_diameter_mm": 58.0, "skin_firmness": "Dense dried scales"},
        "harvest_date": "2026-08-18", "availability_date": "2026-08-23", "preferred_selling_date": "2026-09-12",
        "shelf_life": 90, "location": "Pimpalgaon APMC, Nashik, Maharashtra", "latitude": 20.1684, "longitude": 73.9877,
        "images": ["/crops/onion.jpg"], "description": "Large size red onions with deep red color, stored in ventilated chawl.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_onion_yeola_03",
        "user_id": "usr_farmer_shivaji",
        "farmer_name": "Shivaji Bhor",
        "crop": "Onion",
        "crop_category": "Bulb Vegetables",
        "variety": "Bhima Dark Red",
        "grade": "A",
        "quantity": 3000.0,
        "unit": "kg",
        "min_sale_quantity": 300.0,
        "expected_price": 27.0,
        "min_price": 21.0,
        "price_unit": "per_kg",
        "quality_info": {"bulb_diameter_mm": 52.0, "skin_firmness": "Double skinned"},
        "harvest_date": "2026-08-16", "availability_date": "2026-08-21", "preferred_selling_date": "2026-09-11",
        "shelf_life": 90, "location": "Yeola APMC, Nashik, Maharashtra", "latitude": 20.0422, "longitude": 74.4859,
        "images": ["/crops/onion.jpg"], "description": "Excellent keeping quality, ideal for inter-state transit to southern states.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },

    # Sugarcane Mandis (Kolhapur, Sangli, Satara)
    {
        "id": "prod_sugarcane_kolhapur_01",
        "user_id": "usr_farmer_meera",
        "farmer_name": "Meera Jagtap",
        "crop": "Sugarcane",
        "crop_category": "Cash Crops",
        "variety": "Co-86032 (Nira)",
        "grade": "A",
        "quantity": 10000.0,
        "unit": "kg",
        "min_sale_quantity": 1000.0,
        "expected_price": 38.0,
        "min_price": 34.0,
        "price_unit": "per_kg",
        "quality_info": {"brix_pct": 21.5, "fiber_pct": 12.8, "purity_pct": 89.2},
        "harvest_date": "2026-08-26", "availability_date": "2026-08-27", "preferred_selling_date": "2026-08-30",
        "shelf_life": 5, "location": "Kolhapur APMC, Kolhapur, Maharashtra", "latitude": 16.7050, "longitude": 74.2433,
        "images": ["/crops/sugarcane.jpg"], "description": "Freshly cut high-sucrose Co-86032 cane. 21.5% Brix.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_sugarcane_sangli_02",
        "user_id": "usr_farmer_tanaji",
        "farmer_name": "Tanaji Patil",
        "crop": "Sugarcane",
        "crop_category": "Cash Crops",
        "variety": "CoM-0265",
        "grade": "A",
        "quantity": 15000.0,
        "unit": "kg",
        "min_sale_quantity": 2000.0,
        "expected_price": 37.5,
        "min_price": 33.5,
        "price_unit": "per_kg",
        "quality_info": {"brix_pct": 20.8, "fiber_pct": 13.0, "purity_pct": 88.5},
        "harvest_date": "2026-08-27", "availability_date": "2026-08-28", "preferred_selling_date": "2026-08-31",
        "shelf_life": 5, "location": "Sangli APMC, Sangli, Maharashtra", "latitude": 16.8524, "longitude": 74.5815,
        "images": ["/crops/sugarcane.jpg"], "description": "High tonnage Krishna river basin sugarcane for jaggery and sugar mills.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },

    # Jowar Mandis (Solapur, Barshi, Pandharpur)
    {
        "id": "prod_jowar_solapur_01",
        "user_id": "usr_farmer_sunita",
        "farmer_name": "Sunita Shinde",
        "crop": "Jowar",
        "crop_category": "Cereals & Millets",
        "variety": "Maldandi 35-1",
        "grade": "A",
        "quantity": 1600.0,
        "unit": "kg",
        "min_sale_quantity": 100.0,
        "expected_price": 42.0,
        "min_price": 38.0,
        "price_unit": "per_kg",
        "quality_info": {"grain_color": "Pearly white", "moisture_pct": 9.8, "protein_pct": 10.5},
        "harvest_date": "2026-08-15", "availability_date": "2026-08-19", "preferred_selling_date": "2026-09-25",
        "shelf_life": 270, "location": "Solapur APMC, Solapur, Maharashtra", "latitude": 17.6599, "longitude": 75.9064,
        "images": ["/crops/jowar.jpg"], "description": "Authentic Solapur Maldandi 35-1 Jowar. Famous sweet roti taste.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_jowar_barshi_02",
        "user_id": "usr_farmer_tukaram",
        "farmer_name": "Tukaram Mane",
        "crop": "Jowar",
        "crop_category": "Cereals & Millets",
        "variety": "Phule Suchitra",
        "grade": "A",
        "quantity": 2000.0,
        "unit": "kg",
        "min_sale_quantity": 200.0,
        "expected_price": 40.0,
        "min_price": 35.5,
        "price_unit": "per_kg",
        "quality_info": {"grain_color": "White lustrous", "moisture_pct": 9.5, "protein_pct": 10.2},
        "harvest_date": "2026-08-17", "availability_date": "2026-08-21", "preferred_selling_date": "2026-09-26",
        "shelf_life": 270, "location": "Barshi APMC, Solapur, Maharashtra", "latitude": 18.2333, "longitude": 75.6833,
        "images": ["/crops/jowar.jpg"], "description": "Lustrous white Rabi Jowar, cleaned and packed in 50kg bags.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },

    # Bajra Mandis (Ahmednagar, Shrirampur, Rahuri)
    {
        "id": "prod_bajra_ahmednagar_01",
        "user_id": "usr_farmer_dnyaneshwar",
        "farmer_name": "Dnyaneshwar More",
        "crop": "Bajra",
        "crop_category": "Cereals & Millets",
        "variety": "ICTP-8203",
        "grade": "A",
        "quantity": 1800.0,
        "unit": "kg",
        "min_sale_quantity": 100.0,
        "expected_price": 28.0,
        "min_price": 24.0,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 10.5, "damaged_grain_pct": 1.0, "grain_color": "Uniform slate grey"},
        "harvest_date": "2026-08-18", "availability_date": "2026-08-22", "preferred_selling_date": "2026-09-22",
        "shelf_life": 240, "location": "Ahmednagar APMC, Ahmednagar, Maharashtra", "latitude": 19.0952, "longitude": 74.7496,
        "images": ["/crops/bajra.jpg"], "description": "Clean, sun-dried Hybrid Bajra from Ahmednagar. High iron content.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_bajra_shrirampur_02",
        "user_id": "usr_farmer_bhausaheb",
        "farmer_name": "Bhausaheb Vikhe",
        "crop": "Bajra",
        "crop_category": "Cereals & Millets",
        "variety": "Phule Maha-Shakti",
        "grade": "A",
        "quantity": 2200.0,
        "unit": "kg",
        "min_sale_quantity": 200.0,
        "expected_price": 27.5,
        "min_price": 23.5,
        "price_unit": "per_kg",
        "quality_info": {"moisture_pct": 10.0, "damaged_grain_pct": 0.8, "grain_color": "Slate grey"},
        "harvest_date": "2026-08-19", "availability_date": "2026-08-23", "preferred_selling_date": "2026-09-24",
        "shelf_life": 240, "location": "Shrirampur APMC, Ahmednagar, Maharashtra", "latitude": 19.6190, "longitude": 74.6596,
        "images": ["/crops/bajra.jpg"], "description": "Large grain size, zero dust, machine cleaned.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },

    # Rice Mandis (Gondia, Bhandara, Chandrapur)
    {
        "id": "prod_rice_gondia_01",
        "user_id": "usr_farmer_prakash",
        "farmer_name": "Prakash Pawar",
        "crop": "Rice",
        "crop_category": "Cereals & Millets",
        "variety": "Wada Kolam / Paddy Grade A",
        "grade": "A",
        "quantity": 3000.0,
        "unit": "kg",
        "min_sale_quantity": 250.0,
        "expected_price": 38.0,
        "min_price": 33.0,
        "price_unit": "per_kg",
        "quality_info": {"grain_length_mm": 6.8, "broken_pct": 2.5, "moisture_pct": 12.0},
        "harvest_date": "2026-08-10", "availability_date": "2026-08-15", "preferred_selling_date": "2026-09-30",
        "shelf_life": 365, "location": "Gondia APMC, Gondia, Maharashtra", "latitude": 21.4604, "longitude": 80.1961,
        "images": ["/crops/rice.jpg"], "description": "High-purity aromatic Wada Kolam raw paddy rice from Gondia.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    },
    {
        "id": "prod_rice_bhandara_02",
        "user_id": "usr_farmer_chandrashekhar",
        "farmer_name": "Chandrashekhar Meshram",
        "crop": "Rice",
        "crop_category": "Cereals & Millets",
        "variety": "HMT Sona / Grade A",
        "grade": "A",
        "quantity": 4500.0,
        "unit": "kg",
        "min_sale_quantity": 500.0,
        "expected_price": 36.5,
        "min_price": 32.5,
        "price_unit": "per_kg",
        "quality_info": {"grain_length_mm": 6.2, "broken_pct": 2.0, "moisture_pct": 11.8},
        "harvest_date": "2026-08-12", "availability_date": "2026-08-17", "preferred_selling_date": "2026-09-28",
        "shelf_life": 365, "location": "Bhandara APMC, Bhandara, Maharashtra", "latitude": 21.1685, "longitude": 79.6543,
        "images": ["/crops/rice.jpg"], "description": "Slender aromatic HMT Sona rice, aged 6 months, high cooking swell.",
        "language": "Marathi", "status": "ACTIVE", "created_at": datetime.now(timezone.utc).isoformat()
    }
]

async def seed_enriched():
    async with engine.begin() as conn:
        print(f"Upserting {len(ENRICHED_LISTINGS)} enriched multi-mandi produce listings...")
        for p in ENRICHED_LISTINGS:
            await conn.execute(text("""
                INSERT INTO produce (
                    id, workflow_mode, selected_services, user_id, farmer_name, crop, crop_category, variety, grade,
                    quantity, unit, min_sale_quantity, expected_price, min_price,
                    price_unit, quality_info, harvest_date, availability_date,
                    preferred_selling_date, shelf_life, location, latitude,
                    longitude, images, description, language, status, created_at
                ) VALUES (
                    :id, :workflow_mode, :selected_services, :user_id, :farmer_name, :crop, :crop_category, :variety, :grade,
                    :quantity, :unit, :min_sale_quantity, :expected_price, :min_price,
                    :price_unit, :quality_info, :harvest_date, :availability_date,
                    :preferred_selling_date, :shelf_life, :location, :latitude,
                    :longitude, :images, :description, :language, :status, :created_at
                )
                ON CONFLICT (id) DO UPDATE SET
                    expected_price = EXCLUDED.expected_price,
                    min_price = EXCLUDED.min_price,
                    quantity = EXCLUDED.quantity,
                    farmer_name = EXCLUDED.farmer_name,
                    location = EXCLUDED.location,
                    status = EXCLUDED.status;
            """), {
                **p,
                "workflow_mode": "FULL_SUPPLY_CHAIN",
                "selected_services": json.dumps(["STORAGE", "LOGISTICS"]),
                "quality_info": json.dumps(p["quality_info"]),
                "images": json.dumps(p["images"]),
                "harvest_date": p["harvest_date"],
                "availability_date": p["availability_date"],
                "preferred_selling_date": p["preferred_selling_date"],
                "created_at": p["created_at"]
            })
        print(f"Successfully populated {len(ENRICHED_LISTINGS)} produce listings!")

if __name__ == "__main__":
    asyncio.run(seed_enriched())
